# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["brookscunningham@gmail.com"]
description = "hcaptcha demo"
language = "rust"
manifest_version = 2
name = "compute-hcaptcha"
service_id = ""

[local_server]

  [local_server.backends]

    [local_server.backends.httpbin]
      url = "https://httpbin.org"

    [local_server.backends.hcaptchaapi]
      url = "https://hcaptcha.com"
          
  [local_server.dictionaries]
    [local_server.dictionaries.credentials]
      format = "json"
      file="./credentials.json"
      